behaviors:
    TouchCubeMoveGail:
        trainer_type: ppo
        hyperparameters: 
            batch_size: 1024
            buffer_size: 10240
            learning_rate: 3.0e-4
            beta: 5.0e-3
            epsilon: 0.2
            lambd: 0.95
            num_epoch: 3
            learning_rate_schedule: linear
        network_settings:
            normalize: false
            hidden_units: 128
            num_layers: 2
        reward_signals:
            extrinsic: 
                strength: 1
                gamma: 0.99
            #gail:
            #    strength: 0.2
            #    gamma: 0.99
            #    encoding_size: 128
            #    learning_rate: 3.0e-4
            #    use_actions: false
            #    use_vail: false
            #    demo_path: Demos/PincherDemoD.demo
        #behavioral_cloning:
        #    strength: 0.5
        #    demo_path: Demos/PincherDemoD.demo
        max_steps: 100000000
        time_horizon: 64
        summary_freq: 20000
        keep_checkpoints: 5
        checkpoint_interval: 500000
        threaded: true
environment_parameters:
    # 0 = false, 1 = true
    randomBox: 0
    randomCube: 1
    # Recompensas de las diferentes acciones
    rewardGrip: 2
    rewardReleaseInArea: 4
    rewardFinish: 1
    rewardCubeKnockedOff: -1
    rewardCubeReleased: -1
    rewardTime: -1
    curriculumGrip:
        curriculum:
            - name: GripLesson1
              completion_criteria: 
                measure: reward
                behavior: TouchCubeMoveGail
                signal_smoothing: true
                min_lesson_length: 10000
                threshold: 1.2
              value: 0.01
            - name: GripLesson2
              completion_criteria: 
                measure: reward
                behavior: TouchCubeMoveGail
                signal_smoothing: true
                min_lesson_length: 10000
                threshold: 1.2
              value: 0.02
            - name: GripLesson3
              completion_criteria: 
                measure: reward
                behavior: TouchCubeMoveGail
                signal_smoothing: true
                min_lesson_length: 10000
                threshold: 1.2
              value: 0.03
            - name: GripLesson4
              completion_criteria: 
                measure: reward
                behavior: TouchCubeMoveGail
                signal_smoothing: true
                min_lesson_length: 10000
                threshold: 1.2
              value: 0.04
            - name: GripLesson5
              completion_criteria: 
                measure: reward
                behavior: TouchCubeMoveGail
                signal_smoothing: true
                min_lesson_length: 10000
                threshold: 1.2
              value: 0.05
            - name: GripLesson6
              completion_criteria: 
                measure: reward
                behavior: TouchCubeMoveGail
                signal_smoothing: true
                min_lesson_length: 10000
                threshold: 1.2
              value: 0.06
            - name: GripLesson7
              completion_criteria: 
                measure: reward
                behavior: TouchCubeMoveGail
                signal_smoothing: true
                min_lesson_length: 10000
                threshold: 1.2
              value: 0.07
            - name: GripLesson8
              completion_criteria: 
                measure: reward
                behavior: TouchCubeMoveGail
                signal_smoothing: true
                min_lesson_length: 10000
                threshold: 1.2
              value: 0.08
            - name: GripLesson9
              completion_criteria: 
                measure: reward
                behavior: TouchCubeMoveGail
                signal_smoothing: true
                min_lesson_length: 10000
                threshold: 1.2
              value: 0.09
            - name: GripLesson10
              completion_criteria: 
                measure: reward
                behavior: TouchCubeMoveGail
                signal_smoothing: true
                min_lesson_length: 10000
                threshold: 1.2
              value: 0.10
            - name: GripLesson11
              completion_criteria: 
                measure: reward
                behavior: TouchCubeMoveGail
                signal_smoothing: true
                min_lesson_length: 10000
                threshold: 1.2
              value: 0.11
            - name: GripLesson12
              completion_criteria: 
                measure: reward
                behavior: TouchCubeMoveGail
                signal_smoothing: true
                min_lesson_length: 10000
                threshold: 1.2
              value: 0.12
            - name: GripLesson13
              completion_criteria: 
                measure: reward
                behavior: TouchCubeMoveGail
                signal_smoothing: true
                min_lesson_length: 10000
                threshold: 1.2
              value: 0.15
            - name: GripLesson14
              completion_criteria: 
                measure: reward
                behavior: TouchCubeMoveGail
                signal_smoothing: true
                min_lesson_length: 10000
                threshold: 1.2
              value: 0.18
            - name: GripLesson15
              completion_criteria: 
                measure: reward
                behavior: TouchCubeMoveGail
                signal_smoothing: true
                min_lesson_length: 10000
                threshold: 1.2
              value: 0.21
            - name: GripLesson16
              completion_criteria: 
                measure: reward
                behavior: TouchCubeMoveGail
                signal_smoothing: true
                min_lesson_length: 10000
                threshold: 1.2
              value: 0.24
            - name: GripLesson17
              completion_criteria: 
                measure: reward
                behavior: TouchCubeMoveGail
                signal_smoothing: true
                min_lesson_length: 10000
                threshold: 1.2
              value: 0.27
            - name: GripLesson18
              completion_criteria: 
                measure: reward
                behavior: TouchCubeMoveGail
                signal_smoothing: true
                min_lesson_length: 10000
                threshold: 1.2
              value: 0.30
              
              
            

            
            
        
