behaviors:
    TouchCubeMoveGail:
        trainer_type: ppo
        hyperparameters: 
            batch_size: 1024
            buffer_size: 10240
            learning_rate: 3.0e-4
            beta: 5.0e-3
            epsilon: 0.2
            lambd: 0.95
            num_epoch: 3
            learning_rate_schedule: linear
        network_settings:
            normalize: false
            hidden_units: 128
            num_layers: 2
        reward_signals:
            extrinsic: 
                strength: 1
                gamma: 0.99
            #gail:
            #    strength: 0.2
            #    gamma: 0.99
            #    encoding_size: 128
            #    learning_rate: 3.0e-4
            #    use_actions: false
            #    use_vail: false
            #    demo_path: Demos/PincherDemoD.demo
        #behavioral_cloning:
        #    strength: 0.5
        #    demo_path: Demos/PincherDemoD.demo
        max_steps: 10000000
        time_horizon: 64
        summary_freq: 20000
        keep_checkpoints: 5
        checkpoint_interval: 500000
        threaded: true
environment_parameters:
    # 0 = false, 1 = true
    randomBox: 0
    randomCube: 1
    # Recompensas de las diferentes acciones
    rewardGrip: 2
    rewardReleaseInArea: 3
    rewardFinish: 1
    rewardCubeKnockedOff: -1
    rewardCubeReleased: -1
    rewardTime: -1
        
